### ISSUE TITLE
modify department fails

### ISSUE THREAD

**Issue by itay-nvn-nv** [runai-professional-services/runapy#1]
attempting to modify an existing department fails:
```
default_department_id=""
default_nodepool_id=""
default_nodepool_name=""

department = client.departments.update_resources(
    department_id=default_department_id,
    resources=[
        {
        "nodePool": {
            "id": default_nodepool_id,
            "name": default_nodepool_name
        },
        "gpu": {
            "deserved": 4,
            "limit": -1,
            "overQuotaWeight": 4}
        }
    ]
)
```

result:
```
DEBUG:runai.client:Data: [{'nodePool': {'id': '3435', 'name': 'default'}, 'gpu': {'deserved': 4, 'limit': -1, 'overQuotaWeight': 4}, 'cpu': None, 'memory': None}]
DEBUG:runai.client:Making PUT call to: https://envinaclicksso.run.ai/api/v1/org-unit/departments/4515288/resources
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/bin/python/site-packages/runai/controllers.py", line 402, in update_resources
    return self.client.put(path, payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bin/python/site-packages/runai/client.py", line 208, in put
    resp = self.request(self._session.put, url, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bin/python/site-packages/runai/client.py", line 188, in request
    resp = http_method(url=full_url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bin/python/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bin/python/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bin/python/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/bin/python/site-packages/requests/models.py", line 370, in prepare
    self.prepare_body(data, files, json)
  File "/bin/python/site-packages/requests/models.py", line 558, in prepare_body
    body = self._encode_params(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bin/python/site-packages/requests/models.py", line 121, in _encode_params
    for k, vs in to_key_val_list(data):
        ^^^^^
ValueError: too many values to unpack (expected 2)
```

working example (using python requests lib)
```
TOKEN=""
ctrl_plane_url=""
default_department_id=""
default_nodepool_id=""
default_nodepool_name=""

payload = {"description":"","resources":[{"nodePool":{"id":default_nodepool_id,"name":default_nodepool_name},"gpu":{"deserved":6,"limit":-1,"overQuotaWeight":6},"cpu":{"limit":-1},"memory":{"limit":-1,"units":"Mib"}}],"nodeTypes":{}}
department_api = f"{ctrl_plane_url}/api/v1/org-unit/departments/{default_department_id}"
json_payload = json.dumps(payload)
response = requests.request("PUT", department_api, headers={"Authorization": f"Bearer {TOKEN}"}, data=json_payload)
data = json.loads(response.text)
print(f"Modified default environment (GPU: {data["resources"]["gpu"]} )")
```

**Comment by ofir-run-ai** [comment]
Closing this PR as v1 of the project is released very soon and addresses this bug.
